# Generated by Django 3.0.7 on 2020-07-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
